version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Clone UE4"
          no_output_timeout: 600m
          shell: powershell.exe
          command: |
            echo "------------------------------"
            ls 
            pwd
            echo "-------------------------------"
            echo "Start Clone"
            git clone --depth 1 https://377052338888d3ac7525339338ad66add7b2b13d@github.com/EpicGames/UnrealEngine.git
      - run:
          name: "Build UE4"
          no_output_timeout: 600m
          shell: powershell.exe
          command: |
            echo "Start Build"
            cd UnrealEngine
            ./Setup.bat
            ./GenerateProjectFiles.bat
               